### PR TITLE
feature: add option to not output repos which had 0 minutes used

### PR DESCRIPTION
**Pull request by cakeinpanic**
# Description
Hi! This is a great action I'd like to use in my organization. But we have about 1000 repos, and only 200 are using GHA. So the log is huuuuge and it's hard to navigate inside of it.
So I have added additional input to optionally print only repos with more than 0 minutes usage

## Type of change
feature

## How Has This Been Tested?
I tested it locally & using built-in test aciton(great idea to have one) on my organization

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have labelled my PR

### CODE REVIEW

**Comment by cakeinpanic** [comment]
@mononokehime  hi! please take a look

**Review by mononokehime — APPROVED** [review]
Great thank you! We don't have that number of repos in our org (thankfully). This is a really useful improvement.

**Comment by mononokehime** [comment]
Unsure why the GHAs are failing, so merging and will try later

**Comment by cakeinpanic** [comment]
great, thank you!
can you please release a new version?

**Pull request merged**
